server.port: 8081

spring:
  application:
    name: courier-management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:55432/courierdb
    username: postgres
    password: postgres