server.port: 8081

spring:
  application:
    name: courier-management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:55432/courierdb
    username: postgres
    password: postgres

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: courier-management
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:
          delivery-placed-event:com.nedware.courier.management.domain.event.DeliveryPlacedEvent,
          delivery-picked-up-event:com.jackson.databind.JsonNode,
          delivery-fulfilled-event:com.nedware.courier.management.domain.event.DeliveryFulfilledEvent